server:
  port: 8900

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: product-catalog-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/products/**
          filters:
            - AuthenticationFilter

        - id: product-upload
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/upload, /api/upload/**
          filters:
            - AuthenticationFilter

        - id: product-uploads-static
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/uploads/**

        - id: category-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/categories/**
          filters:
            - AuthenticationFilter

        - id: brand-service
          uri: lb://product-catalog-service
          predicates:
            - Path=/api/brands/**
          filters:
            - AuthenticationFilter
        - id: product-recommendation-service
          uri: lb://product-recommendation-service
          predicates:
            - Path=/api/recommendations/**
          filters:
            - AuthenticationFilter

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - AuthenticationFilter

        - id: payment-service
          uri: lb://order-service
          predicates:
            - Path=/api/payment/**

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**, /api/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 5
                key-resolver: "#{@ipKeyResolver}"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  swagger-ui:
    urls:
      - name: product-service
        url: /product-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: inventory-service
        url: /inventory-service/v3/api-docs
      - name: notification-service
        url: /notification-service/v3/api-docs
